### PR TITLE
feat: Setup Dockerfile (monorepo)

### PR DESCRIPTION
**Pull request by teamchong**
## Description

* Include new unit tests of  https://github.com/forbole/big-dipper-2.0-cosmos/pull/1044
* Move duplicated components / screens into `ui` package
* Update web socket connection, try to fix https://github.com/forbole/big-dipper-2.0-cosmos/issues/1045
* Various bug fixes
* Setup docker images

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.*

I have...

- [X] ran linting
- [X] wrote tests where necessary
- [X] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [X] targeted the correct branch
- [X] provided a link to the relevant issue or specification
- [X] reviewed "Files changed" and left comments if necessary
- [X] confirmed all CI checks have passed
- [X] added an entry to the `CHANGELOG.md` file

### CODE REVIEW

**Comment by huichiaotsou** [comment]
hey @teamchong I ran: 
```shell
corepack enable && yarn
yarn turbo run build --filter=web-agoric
yarn dev:web --filter web-agoric
```

and access `localhost:3000/agoric` but I was forwarded to `localhost:3000` and showing desmos.  Did I miss anything or there's something to be fixed? thx

**Comment by teamchong** [comment]
> hey @teamchong I ran:
> 
> ```shell
> corepack enable && yarn
> yarn turbo run build --filter=web-agoric
> yarn dev:web --filter web-agoric
> ```
> 
> and access `localhost:3000/agoric` but I was forwarded to `localhost:3000` and showing desmos. Did I miss anything or there's something to be fixed? thx

try
```
corepack enable && yarn
yarn dev --filter web-agoric
```

**Review by huichiaotsou — APPROVED** [review]
tested LGTM. @teamchong could you solve the conflicts? cheers

**Review by MonikaCat — APPROVED** [review]
tested, LGTM. Can you also resolve the conflict before merging pls? Thanks

**Pull request merged**
