### PR TITLE
feat: wormhole [web-wormhole]

### PR DESCRIPTION
**Pull request by rachelhox**
## Description

Closes: [BDU-852](https://forbole.atlassian.net/browse/BDU-852)

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] ran linting via `yarn lint`
- [x] wrote tests where necessary
- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] targeted the correct branch
- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed
- [x] added a changeset via [`yarn && yarn changeset`](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md)

[BDU-852]: https://forbole.atlassian.net/browse/BDU-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rachelhox** [comment]
updated color scheme:
image
Reference: [Wormhole brand book](https://wormhole.com/brand/)

**Comment by kwunyeung** [comment]
@rachelhox should this PR be broken down into several PRs? I see it includes updated yarn cache, updated web assets and the directory of `app-wormhole`. It becomes very complicated in a single PR.

**Comment by rachelhox** [comment]
> @rachelhox should this PR be broken down into several PRs? I see it includes updated yarn cache, updated web assets and the directory of `app-wormhole`. It becomes very complicated in a single PR.

the `yarn cache` commit is getting the cache up to date with the current yarn cache on `main` considering this PR was opened 2 weeks ago and versions bump has been merged to `main`, the current repository is a monorepo structure so each directory under `apps` is a project for each chain, web assets update contains logos for Human.ai. @kwunyeung

**Comment by kwunyeung** [comment]
The description of the PR become not very clear as it only points to the Jira ticket regarding Wormhole BD setup. Is there a ticket for updating humans.ai?

**Comment by rachelhox** [comment]
> 

the `networks.json` was auto generated by the bash script, the file actually belongs [here](https://github.com/forbole/big-dipper-networks/blob/main/networks.json) and no longer has any effect on this code base. I will remove the file generation command on the script. Now the file has been removed, please review and let me know if there's any issues:) @kwunyeung

**Pull request merged**
