### PR TITLE
feat: humansai testnet [web-humansai]

### PR DESCRIPTION
**Pull request by rachelhox**
## Description

Closes:
[BDU-817](https://forbole.atlassian.net/browse/BDU-817)

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] ran linting via `yarn lint`
- [x] wrote tests where necessary
- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] targeted the correct branch
- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed
- [x] added a changeset via [`yarn && yarn changeset`](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md)

[BDU-817]: https://forbole.atlassian.net/browse/BDU-817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by MonikaCat** [comment]
Hey @rachelhox can you update the tokenomics component (currently is showing `NaN` values)  and `supply`, `community_pool` values pls? The data is available in db, thanks ^^

**Comment by rachelhox** [comment]
@teamchong 

> Hey @rachelhox can you update the tokenomics component (currently is showing `NaN` values) and `supply`, `community_pool` values pls? The data is available in db, thanks ^^

@teamchong could you take a look and fix this issue? `numeral` package cannot handle big number so we need to handle this with another package

**Comment by teamchong** [comment]
> @teamchong
> 
> > Hey @rachelhox can you update the tokenomics component (currently is showing `NaN` values) and `supply`, `community_pool` values pls? The data is available in db, thanks ^^
> 
> @teamchong could you take a look and fix this issue? `numeral` package cannot handle big number so we need to handle this with another package

@rachelhox I resolved the NaN issue in the tokenomics component. The fix involved changing the formatting from `numeral(value).format('0,0')` to `numeral(value).format('0,0a')`.

However, it's important to note that this change will be applied to all workspaces. Before proceeding, please review and confirm if this modification aligns with the intended behavior and formatting requirements.

**Review by teamchong — APPROVED** [review]

**Comment by rachelhox** [comment]
> Hey @rachelhox can you merge the latest changes from main branch to update the login component (or remove it since this is testnet)?

going to open a new PR now for humansai, the merge conflict would take a while to resolve

**Comment by MonikaCat** [comment]
Suppressed by https://github.com/forbole/big-dipper-2.0-cosmos/pull/1253

**Pull request closed without merging**
