### PR TITLE
feat: Shared translations for workspaces [web-band]

### PR DESCRIPTION
**Pull request by teamchong**
## Description

Closes: #1241 [BDU-947](https://forbole.atlassian.net/browse/BDU-947)

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [X] ran linting via `yarn lint`
- [X] wrote tests where necessary
- [X] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [X] targeted the correct branch
- [X] provided a link to the relevant issue or specification
- [X] reviewed "Files changed" and left comments if necessary
- [X] confirmed all CI checks have passed
- [X] added a changeset via [`yarn && yarn changeset`](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md)

[BDU-947]: https://forbole.atlassian.net/browse/BDU-947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by MonikaCat** [comment]
LGTM @teamchong could you also please resolve the conflicts before we merge? Thanks ^^

**Review by MonikaCat — DISMISSED** [review]

**Review by rachelhox — DISMISSED** [review]
LGTM

**Comment by teamchong** [comment]
> @teamchong are we good to merge this? Or would you need to fix some mere conflicts before merging this branch to `main`?

Resolved

**Review by rachelhox — APPROVED** [review]
LGTM

**Pull request merged**
