### PR TITLE
feat: add login with Keplr and WalletConnect [web-desmos]

### PR DESCRIPTION
**Pull request by MonikaCat**
## Description

Closes: #XXXX
[BDU-669](https://forbole.atlassian.net/browse/BDU-669)
[BDU-670](https://forbole.atlassian.net/browse/BDU-670)
[BDU-650](https://forbole.atlassian.net/browse/BDU-650)
[BDU-651](https://forbole.atlassian.net/browse/BDU-651)

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] ran linting via `yarn lint`
- [x] wrote tests where necessary
- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [x] targeted the correct branch
- [x] provided a link to the relevant issue or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed
- [x] added a changeset via [`yarn && yarn changeset`](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md)

[BDU-651]: https://forbole.atlassian.net/browse/BDU-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BDU-669]: https://forbole.atlassian.net/browse/BDU-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BDU-670]: https://forbole.atlassian.net/browse/BDU-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BDU-650]: https://forbole.atlassian.net/browse/BDU-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by teamchong — APPROVED** [review]
LGTM
made a few changes
- update the locales
- use a static config for keplr settings
- update e2e testing
- update jest testing

**Comment by MonikaCat** [comment]
Hi @teamchong this PR shouldn't be merged yet, there are still things that needs to be updated (I talked about it with @rachelhox before..):
- The log in button needs to be updated to have the same text and size as in the design

Current:
Screenshot 2023-05-08 at 9 22 04 AM

Design:
Screenshot 2023-05-08 at 9 22 54 AM


- The account drop down button after login needs to be updated to the latest design

Current:
Screenshot 2023-05-08 at 9 28 15 AM

Design:
Screenshot 2023-05-08 at 9 23 42 AM

**Comment by rachelhox** [comment]
> Hi @teamchong this PR shouldn't be merged yet, there are still things that needs to be updated (I talked about it with @rachelhox before..):
> 
> * The log in button needs to be updated to have the same text and size as in the design
> 
> Current: Screenshot 2023-05-08 at 9 22 04 AM
> 
> Design: Screenshot 2023-05-08 at 9 22 54 AM
> 
> * The account drop down button after login needs to be updated to the latest design
> 
> Current: Screenshot 2023-05-08 at 9 28 15 AM
> 
> Design: Screenshot 2023-05-08 at 9 23 42 AM

@MonikaCat should we re-open and revert this PR? Or I can open a new PR and quickly revise the UI for the log-in state?

**Comment by MonikaCat** [comment]
@rachelhox I think it's better to open new PR targeting those changes, thanks!

**Pull request merged**
